# Page settings

baseURL = "https://jlevesy.github.io/"
languageCode = "en"
title = "/home/jlevesy"
theme = "devresume"

[params]
  author = "Julien Levesy"
  description = "@jlevesy's resume"
  primaryColor = "#FF3366"

  [params.profile]
    enable = true
    name = "Julien Levesy"
    tagline = "Sr Software Engineer / SRE"
    avatar = "avatar.jpg"

  [params.summary]
    enable = true
    text = "Product centered software engineer who loves to learn and adapt. I'm dedicated to build meaningful and reliable products, from the frontend to the infrastructure and from early stage proposals to production, including customer facing support! I strongly believe that teamwork and communication are essential to a successful product and I vouch for RFCs and proposals for decision making (no decisions in meetings). Having lived abroad and traveled a lot, I'm especially at ease with (and definitely looking for!) multicultural and diverse work environements. If you think that I might be a fit feel free to contact me, I'll always be happy to talk to you!"

  [params.contact]
    enable = true
    location = "Lyon (France)"
    [[params.contact.list]]
      icon = "fas fa-phone-square"
      url = "tel:#"
      text = "+33 7 68 03 36 39"
    [[params.contact.list]]
      icon = "fas fa-envelope-square"
      url = "mailto:#"
      text = "contact@jlevesy.net"
    [[params.contact.list]]
      icon = "fas fa-globe"
      url = "https://jlevesy.github.io"
      text = "https://jlevesy.github.io"

  [params.skills]
    enable = true

    [[params.skills.list]]
    title = "Technical"
    [[params.skills.list.items]]
    details = "Golang"
    [[params.skills.list.items]]
    details = "Container orchestration"
    [[params.skills.list.items]]
    details = "Linux and System administration"
    [[params.skills.list.items]]
    details = "Monitoring"
    [[params.skills.list.items]]
    details = "Lead and deliver complex software systems"

    [[params.skills.list]]
    title = "Professional"

    [[params.skills.list.items]]
    details = "Team player"
    [[params.skills.list.items]]
    details = "Effective communication"
    [[params.skills.list.items]]
    details = "Strong problem solver"

  [params.languages]
    enable = true

    [[params.languages.list]]
    name = "French"
    level = "Native"
    [[params.languages.list]]
    name = "English"
    level = "Fluent"
    [[params.languages.list]]
    name = "Spanish"
    level = "Intermediate"

  [params.education]
    enable = true

    [[params.education.list]]
    degree = "MSc in Computer Science"
    university = "Institut National des Sciences Appliquées (INSA) de Lyon"
    dates = "2007 - 2012"

  [params.experience]
    enable = true

    [[params.experience.list]]
      title = "Senior Software Engineer"
      dates = "2018 - now"
      company = "Containous"
      details = "Role description goes here ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus."

    [[params.experience.list]]
      title = "Software Engineer / SRE"
      dates = "2017 - 2018"
      company = "Vivlio (The Ebook Alternative)"
      details = "Role description goes here ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus."

    [[params.experience.list]]
      title = "Software Engineer"
      dates = "2015 - 2017"
      company = "Upfluence"
      details = "Role description goes here ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus."

    [[params.experience.list]]
      title = "Software Engineer"
      dates = "2014 - 2015"
      company = "Worldline by Atos"
      details = "Role description goes here ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus."

    [[params.experience.list]]
      title = "Junior Software Engineer"
      dates = "2012 - 2014"
      company = "AwoX"
      details = "Role description goes here ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus."

  [params.projects]
    enable = true

    [[params.projects.list]]
    title = "Traefik Enterprise Edition"
    meta = "golang, docker, kubernetes, swarmkit"
    tagline = "Traefik Enterprise Edition is a natively distributed verion of Traefik (https://traefik.io) the open source edge router. Leveraging Docker's very own Swarmkit at its core, it provides all the features of the open source version plus several advanced features like native authentication and authorization systems, distributed rate limiting and recently the integration of Containous service mesh implementation, Maesh. More information can be found on the Containous website: https://containo.us/traefikee"

    [[params.projects.list]]
    title = "Upfluence Search Engine"
    meta = "golang ruby python elasticsearch coreos"
    tagline = "You can use this section for your side projects. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim."

    [[params.projects.list]]
    title = "Sind (Swarm In Docker)"
    meta = "golang, Open Source"
    tagline = "You can use this section for your side projects. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim."

    [[params.projects.list]]
    title = "Various Open Source Contributions"
    meta = "golang, rust, c++"
    tagline = "The contributions I'm most proud of are the one I did on firefox's javascript JIT engine where I implemented various optimisations. Recently I've contributed to yaegi (https://github.com/containous/yaegi), Containous's very own golang interpreter and i3-status-rust (https://github.com/greshake/i3-status-rust) because I love i3 and wanted to learn a bit of Rust, and I loved it!"


    [params.information]
      enable = true

        [[params.information.list]]
        title = "Interests"
        details = "Climbing, Running, Photography, Travelling"

    [params.social]
        enable = true

        [[params.social.list]]
        icon = "fab fa-github-square"
        url = "//github.com/jlevesy"
        title = "jlevesy"
        [[params.social.list]]
        icon = "fab fa-linkedin"
        url = "//linkedin.com/in/jlevesy"
        title = "jlevesy"
        [[params.social.list]]
        icon = "fab fa-twitter-square"
        url = "//twitter.com/jlevesy"
        title = "@jlevesy"
