# Page settings

baseURL = "https://jlevesy.github.io/"
languageCode = "en"
title = "/home/jlevesy"
theme = "devresume"

[params]
  author = "Julien Levesy"
  description = "@jlevesy's resume"
  primaryColor = "#FF3366"

  [params.profile]
    enable = true
    name = "Julien Levesy"
    tagline = "Sr Software Engineer / SRE"
    avatar = "avatar.jpg"

  [params.summary]
    enable = true
    text = "Product centered software engineer who loves to learn and adapt. I'm dedicated to build meaningful and reliable products, from the frontend to the infrastructure and from early stage proposals to production, including customer support! I strongly believe that teamwork and communication are essential to a successful product and I vouch for RFCs and proposals for decision making. Having lived abroad and traveled a lot, I'm especially at ease with (and definitely looking for!) multicultural and diverse work environements. If you think that I might be a fit, feel free to contact me! I'll always be happy to talk to you!"

  [params.contact]
    enable = true
    location = "Lyon (France)"
    [[params.contact.list]]
      icon = "fas fa-phone-square"
      url = "tel:#"
      text = "+33 7 68 03 36 39"
    [[params.contact.list]]
      icon = "fas fa-envelope-square"
      url = "mailto:#"
      text = "jlevesy@gmail.com"
    [[params.contact.list]]
      icon = "fas fa-globe"
      url = "https://jlevesy.github.io"
      text = "https://jlevesy.github.io"

  [params.skills]
    enable = true

    [[params.skills.list]]
    title = "Technical"

      [[params.skills.list.items]]
      details = "Golang"
      [[params.skills.list.items]]
      details = "Container orchestration"
      [[params.skills.list.items]]
      details = "Linux and System administration"
      [[params.skills.list.items]]
      details = "Monitoring"
      [[params.skills.list.items]]
      details = "Lead and deliver complex software systems"

    [[params.skills.list]]
    title = "Professional"

      [[params.skills.list.items]]
      details = "Team player"
      [[params.skills.list.items]]
      details = "Effective communication"
      [[params.skills.list.items]]
      details = "Strong problem solver"

  [params.languages]
    enable = true

    [[params.languages.list]]
    name = "French"
    level = "Native"
    [[params.languages.list]]
    name = "English"
    level = "Fluent"
    [[params.languages.list]]
    name = "Spanish"
    level = "Intermediate"

  [params.education]
    enable = true

    [[params.education.list]]
    degree = "MSc in Computer Science"
    university = "Institut National des Sciences Appliquées (INSA) de Lyon"
    dates = "2007 - 2012"

  [params.experience]
    enable = true

    [[params.experience.list]]
      title = "Senior Software Engineer"
      dates = "2018 - now"
      company = "Containous"
      details = "Involved in the Traefik Enterprise team, I contributed to a large majority of the features implemented in the product. I proposed and realized many improvements on it and impacted positively its reliability by leading various efforts like setting up maintaining an end to end testing framework or the systematic writing of unit tests. I am also very involved with the support team and regulary participate on client facing calls. Containous is my first experience in a truly distributed and multicultural company where clear communication and inclusion are a must, and I have to say that I'm loving this kind of environement."

    [[params.experience.list]]
      title = "Software Engineer / SRE"
      dates = "2017 - 2018"
      company = "Vivlio (The Ebook Alternative)"
      details = "Started first as Software developer, my previous experience with server management made me quickly get involved with the operations as well. I was put in charge of important subjects like moving our ecommerce websites to HTTPS, rewriting and extending several applications as developper and setuping a whole new monitoring system based on Datadog. I also had the opportunity to teach an intern during my time and I found it to be a rewarding experience."

    [[params.experience.list]]
      title = "Software Engineer"
      dates = "2015 - 2017"
      company = "Upfluence"
      details = "As the first company employee, I was involved in a small distributed team between Lyon and San Francisco. We built from scratch multiple products around content marketing and native advertising which finaly lead the Upfluence software to be one of the most powerful influencer search engine available. My position was fullstack developer and I worked on a complex applicative stack involving numerous microservices written in 4 major differents languages, golang included. This was also my first experience with production and gave me the opportunity to learn cutting edge subjects like containers, orchestration and distributed systems. I'm always proud to see that 3 years later, Upfluence is a successful company and some of my code is still running at its core!"

    [[params.experience.list]]
      title = "Software Engineer"
      dates = "2014 - 2015"
      company = "Worldline by Atos"
      details = "Worked as developer on a complex application built to refund clients in case of bank bankruptcy. It involved complex business rules and beeing able to handle an important amount of open cases. This was my first experience as web developer, in a large team and in a large company. I gave various talks about test driven development, like https://worldline.github.io/bfi-ecs-coding-dojo/tdd-01/presentation, as I understood how important it is on projects of this scale."

    [[params.experience.list]]
      title = "Junior Software Engineer"
      dates = "2012 - 2014"
      company = "AwoX"
      details = "First experience as software engineer, I had two primary missions in that position. First was to build middleware and user interface application for a \"second screen\" set top box system, using DLNA, linux and web technologies. Second was to build a multiplatform desktop application dedicated to control Awox Striim series devices. It features a DLNA control point, and also custom features like devices zoning and lighting control over network."

  [params.projects]
    enable = true

    [[params.projects.list]]
    title = "Traefik Enterprise Edition"
    meta = "golang, docker, kubernetes, swarmkit"
    tagline = "Traefik Enterprise Edition is a natively distributed verion of Traefik (https://traefik.io) the open source edge router. Leveraging Docker's very own Swarmkit at its core, it provides all the features of the open source version plus several advanced features like native authentication and authorization systems, distributed rate limiting and recently the integration of Containous service mesh implementation, Maesh. More information can be found on the Containous website: https://containo.us/traefikee"

    [[params.projects.list]]
    title = "Upfluence Search Engine"
    meta = "golang ruby python elasticsearch coreos"
    tagline = "The Upfluence search engine allows to easily identify relevant influencers to your brand, get in touch with them, efficiently define an implement an advertising campaign and to finish, easily measure its reach and impact."

    [[params.projects.list]]
    title = "Sind (Swarm In Docker)"
    meta = "golang, Open Source"
    tagline = "Inspired by all the work done in the Kubernetes echosystem and motivated by the fact that we needed for TraefikEE an easy way to create multi nodes swarm environement, I decided to build Sind which is a CLI tool to easily create multi node swarm clusters on top of a docker daemon. Check it out at https://github.com/jlevesy/sind, proposals welcomed!"

    [[params.projects.list]]
    title = "Various Open Source Contributions"
    meta = "golang, rust, c++"
    tagline = "The contributions I'm most proud of are the one I did on firefox's javascript JIT engine where I implemented various optimisations (https://bugzilla.mozilla.org/user_profile?user_id=459021) of the generated code. Recently I've contributed to yaegi (https://github.com/containous/yaegi), Containous's very own golang interpreter and i3-status-rust (https://github.com/greshake/i3-status-rust) because I love i3wm and wanted to learn a bit of Rust !"

  [params.information]
    enable = true

    [[params.information.list]]
    title = "Interests"
    details = "Climbing, Running, Photography, Travelling"

  [params.social]
    enable = true

    [[params.social.list]]
    icon = "fab fa-github-square"
    url = "//github.com/jlevesy"
    title = "jlevesy"
    [[params.social.list]]
    icon = "fab fa-linkedin"
    url = "//linkedin.com/in/jlevesy"
    title = "jlevesy"
    [[params.social.list]]
    icon = "fab fa-twitter-square"
    url = "//twitter.com/jlevesy"
    title = "@jlevesy"
